### Loading Dataset

In [0]:
import sklearn.datasets
import numpy as np

In [0]:
breast_cancer = sklearn.datasets.load_breast_cancer()

In [4]:
type(breast_cancer)

sklearn.utils.Bunch

In [0]:
x = breast_cancer.data
y = breast_cancer.target

In [6]:
type(x)

numpy.ndarray

In [10]:
x.shape, y.shape

((569, 30), (569,))

In [29]:
print(breast_cancer.feature_names)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']

In [0]:
import pandas as pd

In [0]:
df = pd.DataFrame(breast_cancer.data,columns = breast_cancer.feature_names)

In [16]:
df.head()

   mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [0]:
df['class'] = breast_cancer.target

In [18]:
df.head()

   mean radius  mean texture  ...  worst fractal dimension  class
0        17.99         10.38  ...                  0.11890      0
1        20.57         17.77  ...                  0.08902      0
2        19.69         21.25  ...                  0.08758      0
3        11.42         20.38  ...                  0.17300      0
4        20.29         14.34  ...                  0.07678      0

[5 rows x 31 columns]

In [19]:
df.shape

(569, 31)

In [22]:
df.describe()

       mean radius  mean texture  ...  worst fractal dimension       class
count   569.000000    569.000000  ...               569.000000  569.000000
mean     14.127292     19.289649  ...                 0.083946    0.627417
std       3.524049      4.301036  ...                 0.018061    0.483918
min       6.981000      9.710000  ...                 0.055040    0.000000
25%      11.700000     16.170000  ...                 0.071460    0.000000
50%      13.370000     18.840000  ...                 0.080040    1.000000
75%      15.780000     21.800000  ...                 0.092080    1.000000
max      28.110000     39.280000  ...                 0.207500    1.000000

[8 rows x 31 columns]

In [24]:
df['class'].value_counts()

1    357
0    212
Name: class, dtype: int64

In [28]:
print(breast_cancer.target_names)

['malignant' 'benign']

### Split Data

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x = df.drop('class',axis = 1)
y = df['class']

In [0]:
x_train,x_test, y_train,y_test = train_test_split(x,y)

In [34]:
x_train.shape

(426, 30)

In [35]:
x_train.head()

     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
546        10.32         16.35  ...          0.2681                  0.07399
427        10.80         21.98  ...          0.2965                  0.07662
385        14.60         23.29  ...          0.2477                  0.06836
209        15.27         12.91  ...          0.2320                  0.07474
223        15.75         20.25  ...          0.3993                  0.10640

[5 rows x 30 columns]

In [36]:
x_train.describe()

       mean radius  mean texture  ...  worst symmetry  worst fractal dimension
count   426.000000    426.000000  ...      426.000000               426.000000
mean     14.103636     19.140282  ...        0.289329                 0.083685
std       3.489379      4.122760  ...        0.061226                 0.018396
min       7.760000      9.710000  ...        0.156500                 0.055040
25%      11.682500     16.237500  ...        0.248725                 0.071180
50%      13.270000     18.725000  ...        0.281100                 0.079485
75%      15.745000     21.597500  ...        0.318275                 0.091525
max      28.110000     33.810000  ...        0.663800                 0.207500

[8 rows x 30 columns]

In [37]:
print(x.shape,x_train.shape,x_test.shape)

(569, 30) (426, 30) (143, 30)

In [0]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1)

In [39]:
print(x.shape,x_train.shape,x_test.shape)

(569, 30) (512, 30) (57, 30)

In [40]:
print(y.mean(),y_train.mean(),y_test.mean())

0.6274165202108963 0.62109375 0.6842105263157895

Maintaining class ratios in train and test split as in the main dataset as much as possible.

In [0]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1,stratify=y)

In [42]:
print(y.mean(),y_train.mean(),y_test.mean())

0.6274165202108963 0.626953125 0.631578947368421

To have same split always (so that results are reproducible in future runs of the algorithm), we need to send random state argument, which is also referred to as seed of the splitter. The state doesn't matter.

In [0]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1,stratify=y,random_state=1)